/** Example inputs for the 'Try an example' feature. */
export const SAMPLES: Record<string, string>={
'Java: NoClassDefFoundError (LWJGL)':'---- Minecraft Crash Report ----\nDescription: Initializing game\n\njava.lang.NoClassDefFoundError: org/lwjgl/sdl/SDL\n\tat net.minecraft.client.Minecraft.<init>(Minecraft.java:512)\n\tat net.minecraft.client.main.Main.main(Main.java:210)\nCaused by: java.lang.ClassNotFoundException: org.lwjgl.sdl.SDL\n\tat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)\n\n-- System Details --\n\tMinecraft Version: 1.21.1\n\tOperating System: Windows 11 (amd64) version 10.0\n\tJava Version: 21.0.5, Microsoft\n',
'Java: NullPointerException':'Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "name" is null\n\tat com.example.app.UserService.format(UserService.java:42)\n\tat com.example.app.Main.main(Main.java:11)\n',
'Java: OutOfMemoryError':'Exception in thread "main" java.lang.OutOfMemoryError: Java heap space\n\tat java.base/java.util.Arrays.copyOf(Arrays.java:3512)\n\tat com.example.Loader.readAll(Loader.java:88)\n',
'Python: ModuleNotFoundError':'Traceback (most recent call last):\n  File "app.py", line 3, in <module>\n    import requests\nModuleNotFoundError: No module named \'requests\'\n',
'Python: KeyError':'Traceback (most recent call last):\n  File "main.py", line 14, in load\n    return cfg["database"]\nKeyError: \'database\'\n',
'JavaScript: TypeError':"TypeError: Cannot read properties of undefined (reading 'map')\n    at renderList (/app/src/list.js:42:17)\n    at main (/app/src/index.js:8:3)\n",
'JavaScript: ReferenceError':'ReferenceError: fetchUser is not defined\n    at init (/app/main.js:9:5)\n',
'Minecraft: Fabric dependency error':'[main/ERROR]: Incompatible mods found!\nMod resolution failed\n - Mod \'Example Mod\' (examplemod) 1.4.0 requires version 0.100.0 or later of fabric-api, which is missing!\nMinecraft 1.21.1, Fabric Loader 0.16.5, Java 21.0.5\n',
'Minecraft: Mixin error':'---- Minecraft Crash Report ----\norg.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered\nCaused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on onRender could not find any targets matching in net.minecraft.client.gui.hud.InGameHud. [examplemod.mixins.json:HudMixin]\n\tat net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:100)\n\tat com.example.examplemod.mixin.HudMixin.onRender(HudMixin.java:21)\n-- System Details --\n\tMinecraft Version: 1.21.1\n\tJava Version: 21.0.5, Microsoft\n\tFabric Mods:\n\t\tfabricloader: Fabric Loader 0.16.5\n\t\texamplemod: Example Mod 1.4.0\n',
'Minecraft: Java version mismatch':'Error: LinkageError occurred while loading main class net.fabricmc.loader.impl.launch.knot.KnotClient\njava.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0\n'};

